export const buildDefaultFormState = ({ profile, user, type = "expense" }) => ({
  date: "",
  amount: "",
  currency: profile?.currency || "EUR",
  merchant: "",
  description: "",
  categoryId: "",
  category: "",
  subcategoryId: "",
  subcategory: "",
  spendType: "",
  incomeStability: "",
  paymentMethod: "",
  paymentMethodId: "",
  accountId: "",
  fromAccountId: "",
  toAccountId: "",
  allocation: false,
  paidByUserId: user?.uid || "",
  type
});
